export const kanjiData = [
  {
    character: "日",
    meaning: "day, sun",
    onyomi: ["ニチ", "ジツ"],
    kunyomi: ["ひ", "-び", "-か"],
    jlptLevel: "N5",
    strokeCount: 4,
    examples: [
      { word: "日本", reading: "にほん", meaning: "Japan" },
      { word: "今日", reading: "きょう", meaning: "today" },
      { word: "日曜日", reading: "にちようび", meaning: "Sunday" },
    ],
    radicals: [{ character: "日", meaning: "sun", reading: "ひ" }],
    similar: ["目", "白", "自"],
  },
  {
    character: "一",
    meaning: "one",
    onyomi: ["イチ", "イツ"],
    kunyomi: ["ひと-", "ひと.つ"],
    jlptLevel: "N5",
    strokeCount: 1,
    examples: [
      { word: "一人", reading: "ひとり", meaning: "one person" },
      { word: "一日", reading: "いちにち", meaning: "one day" },
      { word: "一月", reading: "いちがつ", meaning: "January" },
    ],
    radicals: [{ character: "一", meaning: "one", reading: "いち" }],
    similar: ["二", "三", "十"],
  },
  {
    character: "人",
    meaning: "person",
    onyomi: ["ジン", "ニン"],
    kunyomi: ["ひと"],
    jlptLevel: "N5",
    strokeCount: 2,
    examples: [
      { word: "人間", reading: "にんげん", meaning: "human" },
      { word: "日本人", reading: "にほんじん", meaning: "Japanese person" },
      { word: "一人", reading: "ひとり", meaning: "one person" },
    ],
    radicals: [{ character: "人", meaning: "person", reading: "ひと" }],
    similar: ["入", "八", "大"],
  },
  {
    character: "大",
    meaning: "big, large",
    onyomi: ["ダイ", "タイ"],
    kunyomi: ["おお-", "おお.きい"],
    jlptLevel: "N5",
    strokeCount: 3,
    examples: [
      { word: "大学", reading: "だいがく", meaning: "university" },
      { word: "大きい", reading: "おおきい", meaning: "big" },
      { word: "大人", reading: "おとな", meaning: "adult" },
    ],
    radicals: [{ character: "大", meaning: "big", reading: "だい" }],
    similar: ["太", "犬", "天"],
  },
  {
    character: "山",
    meaning: "mountain",
    onyomi: ["サン"],
    kunyomi: ["やま"],
    jlptLevel: "N5",
    strokeCount: 3,
    examples: [
      { word: "山田", reading: "やまだ", meaning: "Yamada (surname)" },
      { word: "富士山", reading: "ふじさん", meaning: "Mt. Fuji" },
      { word: "火山", reading: "かざん", meaning: "volcano" },
    ],
    radicals: [{ character: "山", meaning: "mountain", reading: "やま" }],
    similar: ["出", "岩", "峠"],
  },
  {
    character: "川",
    meaning: "river",
    onyomi: ["セン"],
    kunyomi: ["かわ"],
    jlptLevel: "N5",
    strokeCount: 3,
    examples: [
      { word: "川口", reading: "かわぐち", meaning: "Kawaguchi (place name)" },
      { word: "小川", reading: "おがわ", meaning: "small river, stream" },
      { word: "河川", reading: "かせん", meaning: "rivers" },
    ],
    radicals: [{ character: "川", meaning: "river", reading: "かわ" }],
    similar: ["州", "小", "水"],
  },
  {
    character: "水",
    meaning: "water",
    onyomi: ["スイ"],
    kunyomi: ["みず"],
    jlptLevel: "N5",
    strokeCount: 4,
    examples: [
      { word: "水曜日", reading: "すいようび", meaning: "Wednesday" },
      { word: "水泳", reading: "すいえい", meaning: "swimming" },
      { word: "飲み水", reading: "のみみず", meaning: "drinking water" },
    ],
    radicals: [{ character: "水", meaning: "water", reading: "みず" }],
    similar: ["氷", "永", "泳"],
  },
  {
    character: "火",
    meaning: "fire",
    onyomi: ["カ"],
    kunyomi: ["ひ"],
    jlptLevel: "N5",
    strokeCount: 4,
    examples: [
      { word: "火曜日", reading: "かようび", meaning: "Tuesday" },
      { word: "火山", reading: "かざん", meaning: "volcano" },
      { word: "花火", reading: "はなび", meaning: "fireworks" },
    ],
    radicals: [{ character: "火", meaning: "fire", reading: "ひ" }],
    similar: ["灯", "炎", "災"],
  },
  {
    character: "木",
    meaning: "tree, wood",
    onyomi: ["モク", "ボク"],
    kunyomi: ["き", "こ-"],
    jlptLevel: "N5",
    strokeCount: 4,
    examples: [
      { word: "木曜日", reading: "もくようび", meaning: "Thursday" },
      { word: "木村", reading: "きむら", meaning: "Kimura (surname)" },
      { word: "樹木", reading: "じゅもく", meaning: "trees" },
    ],
    radicals: [{ character: "木", meaning: "tree", reading: "き" }],
    similar: ["本", "森", "林"],
  },
  {
    character: "金",
    meaning: "gold, money",
    onyomi: ["キン", "コン"],
    kunyomi: ["かね", "かな-", "-がね"],
    jlptLevel: "N5",
    strokeCount: 8,
    examples: [
      { word: "金曜日", reading: "きんようび", meaning: "Friday" },
      { word: "お金", reading: "おかね", meaning: "money" },
      { word: "金持ち", reading: "かねもち", meaning: "rich person" },
    ],
    radicals: [{ character: "金", meaning: "gold", reading: "きん" }],
    similar: ["銀", "鉄", "針"],
  },
]

