export const lessonsData = [
  // ===== NIVEAU DÉBUTANT (100 leçons) =====
  // Bases et introduction (1-10)
  {
    id: 1,
    title: "Introduction à la langue japonaise",
    description: "Découvrez les bases de la langue japonaise, son histoire et ses particularités.",
    level: "débutant",
    category: "Introduction",
    duration: "20 min",
    progress: 0,
  },
  {
    id: 2,
    title: "Les systèmes d'écriture japonais",
    description: "Aperçu des trois systèmes d'écriture : Hiragana, Katakana et Kanji.",
    level: "débutant",
    category: "Écriture",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 3,
    title: "Bases du Hiragana - Partie 1",
    description: "Apprenez les premiers caractères Hiragana (あ à さ).",
    level: "débutant",
    category: "Écriture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 4,
    title: "Bases du Hiragana - Partie 2",
    description: "Continuez avec les caractères Hiragana (た à ほ).",
    level: "débutant",
    category: "Écriture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 5,
    title: "Bases du Hiragana - Partie 3",
    description: "Terminez l'apprentissage des caractères Hiragana (ま à ん).",
    level: "débutant",
    category: "Écriture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 6,
    title: "Salutations et présentations",
    description: "Apprenez à vous présenter et à saluer en japonais.",
    level: "débutant",
    category: "Conversation",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 7,
    title: "Bases du Katakana - Partie 1",
    description: "Apprenez les premiers caractères Katakana (ア à サ).",
    level: "débutant",
    category: "Écriture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 8,
    title: "Bases du Katakana - Partie 2",
    description: "Continuez avec les caractères Katakana (タ à ホ).",
    level: "débutant",
    category: "Écriture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 9,
    title: "Bases du Katakana - Partie 3",
    description: "Terminez l'apprentissage des caractères Katakana (マ à ン).",
    level: "débutant",
    category: "Écriture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 10,
    title: "Prononciation japonaise",
    description: "Maîtrisez la prononciation des voyelles, consonnes et accents japonais.",
    level: "débutant",
    category: "Prononciation",
    duration: "25 min",
    progress: 0,
  },

  // Grammaire de base (11-30)
  {
    id: 11,
    title: "Structure de phrase basique",
    description: "Apprenez la structure fondamentale des phrases japonaises (sujet-objet-verbe).",
    level: "débutant",
    category: "Grammaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 12,
    title: "Particules は et が",
    description: "Comprenez la différence entre les particules de sujet は et が.",
    level: "débutant",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 13,
    title: "Particules を, に et で",
    description: "Apprenez à utiliser les particules を (objet), に (direction/lieu) et で (moyen/lieu d'action).",
    level: "débutant",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 14,
    title: "Particules へ, から et まで",
    description: "Maîtrisez les particules de direction へ, d'origine から et de limite まで.",
    level: "débutant",
    category: "Grammaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 15,
    title: "Verbes - Groupe 1 (Verbes en う)",
    description: "Introduction aux verbes du groupe 1 (verbes se terminant en う).",
    level: "débutant",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 16,
    title: "Verbes - Groupe 2 (Verbes en る)",
    description: "Introduction aux verbes du groupe 2 (verbes se terminant en る).",
    level: "débutant",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 17,
    title: "Verbes - Groupe 3 (Verbes irréguliers)",
    description: "Apprenez les verbes irréguliers comme する et 来る.",
    level: "débutant",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 18,
    title: "Forme polie (masu) des verbes",
    description: "Apprenez à conjuguer les verbes à la forme polie (masu).",
    level: "débutant",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 19,
    title: "Forme négative des verbes",
    description: "Comment exprimer la négation avec les verbes japonais.",
    level: "débutant",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 20,
    title: "Forme passée des verbes",
    description: "Conjugaison des verbes au passé (affirmatif et négatif).",
    level: "débutant",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 21,
    title: "Adjectifs en い",
    description: "Apprenez les adjectifs en い et leur conjugaison.",
    level: "débutant",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 22,
    title: "Adjectifs en な",
    description: "Apprenez les adjectifs en な et leur conjugaison.",
    level: "débutant",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 23,
    title: "Forme négative des adjectifs",
    description: "Comment exprimer la négation avec les adjectifs japonais.",
    level: "débutant",
    category: "Grammaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 24,
    title: "Forme passée des adjectifs",
    description: "Conjugaison des adjectifs au passé (affirmatif et négatif).",
    level: "débutant",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 25,
    title: "Noms et prédicats nominaux",
    description: "Utilisation des noms dans les phrases et la copule です.",
    level: "débutant",
    category: "Grammaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 26,
    title: "Questions en japonais",
    description: "Apprenez à poser des questions avec la particule か et les mots interrogatifs.",
    level: "débutant",
    category: "Grammaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 27,
    title: "Expression de l'existence: ある et いる",
    description: "Différence entre ある (objets inanimés) et いる (êtres vivants).",
    level: "débutant",
    category: "Grammaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 28,
    title: "Particule possessive の",
    description: "Utilisation de の pour exprimer la possession et les relations.",
    level: "débutant",
    category: "Grammaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 29,
    title: "Particules も et と",
    description: "Utilisation de も (aussi) et と (avec/et).",
    level: "débutant",
    category: "Grammaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 30,
    title: "Particules や et か",
    description: "Utilisation de や (énumération non exhaustive) et か (ou).",
    level: "débutant",
    category: "Grammaire",
    duration: "35 min",
    progress: 0,
  },

  // Vocabulaire de base (31-50)
  {
    id: 31,
    title: "Nombres et comptage - Partie 1",
    description: "Apprenez les nombres de 1 à 100 en japonais.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 32,
    title: "Nombres et comptage - Partie 2",
    description: "Nombres au-delà de 100 et compteurs japonais de base.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 33,
    title: "Jours de la semaine",
    description: "Apprenez les noms des jours de la semaine en japonais.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "20 min",
    progress: 0,
  },
  {
    id: 34,
    title: "Mois et dates",
    description: "Vocabulaire des mois et comment exprimer les dates.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 35,
    title: "Heure et expressions temporelles",
    description: "Comment dire l'heure et utiliser les expressions de temps.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 36,
    title: "Couleurs",
    description: "Vocabulaire des couleurs et leur utilisation.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 37,
    title: "Famille et relations",
    description: "Vocabulaire des membres de la famille et des relations personnelles.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 38,
    title: "Corps humain",
    description: "Vocabulaire des parties du corps.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 39,
    title: "Vêtements",
    description: "Vocabulaire des vêtements et accessoires.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 40,
    title: "Nourriture et boissons - Partie 1",
    description: "Vocabulaire de base pour la nourriture et les boissons.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 41,
    title: "Nourriture et boissons - Partie 2",
    description: "Plats japonais traditionnels et expressions culinaires.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 42,
    title: "Lieux et bâtiments",
    description: "Vocabulaire des lieux, bâtiments et points d'intérêt.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 43,
    title: "Transports",
    description: "Vocabulaire des moyens de transport et expressions associées.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 44,
    title: "Météo et saisons",
    description: "Vocabulaire de la météo et des quatre saisons.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 45,
    title: "Animaux",
    description: "Vocabulaire des animaux domestiques et sauvages.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 46,
    title: "Pays et nationalités",
    description: "Noms des pays et expressions des nationalités.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 47,
    title: "Professions",
    description: "Vocabulaire des métiers et professions.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 48,
    title: "Adjectifs courants",
    description: "Les adjectifs les plus utilisés en japonais.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 49,
    title: "Verbes d'action courants",
    description: "Les verbes d'action les plus utilisés en japonais.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 50,
    title: "Adverbes et expressions de fréquence",
    description: "Adverbes et expressions pour indiquer la fréquence et l'intensité.",
    level: "débutant",
    category: "Vocabulaire",
    duration: "30 min",
    progress: 0,
  },

  // Conversation et situations pratiques (51-70)
  {
    id: 51,
    title: "Au restaurant",
    description: "Vocabulaire et expressions utiles pour commander au restaurant.",
    level: "débutant",
    category: "Conversation",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 52,
    title: "Faire des achats",
    description: "Expressions utiles pour faire du shopping et négocier.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 53,
    title: "Demander son chemin",
    description: "Comment demander et donner des directions en japonais.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 54,
    title: "À l'hôtel",
    description: "Vocabulaire et expressions utiles pour séjourner à l'hôtel.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 55,
    title: "Transports en commun",
    description: "Comment utiliser les transports en commun au Japon.",
    level: "débutant",
    category: "Conversation",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 56,
    title: "Chez le médecin",
    description: "Vocabulaire médical et expressions pour décrire des symptômes.",
    level: "débutant",
    category: "Conversation",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 57,
    title: "Téléphoner en japonais",
    description: "Expressions utiles pour les conversations téléphoniques.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 58,
    title: "Invitations et rendez-vous",
    description: "Comment inviter quelqu'un et fixer un rendez-vous.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 59,
    title: "Exprimer ses goûts",
    description: "Comment parler de ce que vous aimez et n'aimez pas.",
    level: "débutant",
    category: "Conversation",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 60,
    title: "Parler de ses hobbies",
    description: "Vocabulaire des loisirs et comment en parler.",
    level: "débutant",
    category: "Conversation",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 61,
    title: "Décrire les personnes",
    description: "Comment décrire l'apparence et la personnalité.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 62,
    title: "Parler de la météo",
    description: "Expressions courantes pour discuter de la météo.",
    level: "débutant",
    category: "Conversation",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 63,
    title: "Félicitations et vœux",
    description: "Expressions pour les occasions spéciales et les fêtes.",
    level: "débutant",
    category: "Conversation",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 64,
    title: "Excuses et remerciements",
    description: "Différentes façons de s'excuser et de remercier en japonais.",
    level: "débutant",
    category: "Conversation",
    duration: "25 min",
    progress: 0,
  },
  {
    id: 65,
    title: "Demander et donner l'autorisation",
    description: "Comment demander la permission et répondre à ces demandes.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 66,
    title: "Exprimer son opinion",
    description: "Comment donner votre avis de manière simple.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 67,
    title: "Faire des suggestions",
    description: "Comment proposer des idées et des activités.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 68,
    title: "Exprimer des émotions",
    description: "Vocabulaire et expressions pour parler de vos sentiments.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 69,
    title: "Parler de ses projets",
    description: "Comment discuter de vos plans futurs.",
    level: "débutant",
    category: "Conversation",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 70,
    title: "Raconter sa journée",
    description: "Vocabulaire et structures pour parler de vos activités quotidiennes.",
    level: "débutant",
    category: "Conversation",
    duration: "35 min",
    progress: 0,
  },

  // Kanji de base (71-85)
  {
    id: 71,
    title: "Introduction aux Kanji",
    description: "Histoire, structure et principes de base des Kanji.",
    level: "débutant",
    category: "Kanji",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 72,
    title: "Kanji de base - Partie 1",
    description: "Premiers Kanji simples : 一, 二, 三, 四, 五, 六, 七, 八, 九, 十",
    level: "débutant",
    category: "Kanji",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 73,
    title: "Kanji de base - Partie 2",
    description: "Kanji élémentaires : 人, 大, 小, 中, 山, 川, 日, 月, 火, 水",
    level: "débutant",
    category: "Kanji",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 74,
    title: "Kanji de base - Partie 3",
    description: "Suite des Kanji fondamentaux : 木, 林, 森, 田, 口, 目, 耳, 手, 足, 力",
    level: "débutant",
    category: "Kanji",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 75,
    title: "Kanji de base - Partie 4",
    description: "Kanji courants : 上, 下, 左, 右, 前, 後, 東, 西, 南, 北",
    level: "débutant",
    category: "Kanji",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 76,
    title: "Kanji de base - Partie 5",
    description: "Kanji utiles : 入, 出, 立, 休, 先, 生, 男, 女, 子, 父",
    level: "débutant",
    category: "Kanji",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 77,
    title: "Kanji de base - Partie 6",
    description: "Kanji supplémentaires : 母, 友, 見, 聞, 言, 話, 読, 書, 食, 飲",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 78,
    title: "Kanji de base - Partie 7",
    description: "Kanji pour les lieux : 学, 校, 店, 社, 家, 院, 駅, 国, 町, 市",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 79,
    title: "Kanji de base - Partie 8",
    description: "Kanji pour le temps : 年, 月, 週, 日, 時, 分, 午, 前, 後, 今",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 80,
    title: "Kanji de base - Partie 9",
    description: "Kanji pour les actions : 行, 来, 帰, 歩, 走, 止, 持, 待, 買, 売",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 81,
    title: "Kanji de base - Partie 10",
    description: "Kanji pour les qualités : 新, 古, 高, 低, 長, 短, 大, 小, 多, 少",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 82,
    title: "Kanji de base - Partie 11",
    description: "Kanji pour les sentiments : 好, 愛, 思, 考, 怒, 楽, 苦, 悲, 嬉, 寂",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 83,
    title: "Kanji de base - Partie 12",
    description: "Kanji pour la nature : 天, 空, 雨, 雪, 風, 雲, 海, 川, 山, 石",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 84,
    title: "Kanji de base - Partie 13",
    description: "Kanji pour les objets quotidiens : 本, 紙, 鉛, 筆, 傘, 鍵, 電, 話, 机, 椅",
    level: "débutant",
    category: "Kanji",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 85,
    title: "Kanji de base - Partie 14",
    description: "Révision et pratique des Kanji appris.",
    level: "débutant",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },

  // Culture japonaise (86-100)
  {
    id: 86,
    title: "Introduction à la culture japonaise",
    description: "Aperçu général de la culture et des traditions japonaises.",
    level: "débutant",
    category: "Culture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 87,
    title: "Étiquette japonaise",
    description: "Règles de politesse et comportements attendus au Japon.",
    level: "débutant",
    category: "Culture",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 88,
    title: "Fêtes et célébrations japonaises",
    description: "Principales fêtes et événements culturels au Japon.",
    level: "débutant",
    category: "Culture",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 89,
    title: "Cuisine japonaise",
    description: "Introduction aux plats traditionnels et à l'art culinaire japonais.",
    level: "débutant",
    category: "Culture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 90,
    title: "Arts traditionnels japonais",
    description: "Aperçu des arts comme l'ikebana, l'origami, la calligraphie.",
    level: "débutant",
    category: "Culture",
    duration: "30   l'origami, la calligraphie.",
    level: "débutant",
    category: "Culture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 91,
    title: "Musique et instruments japonais",
    description: "Découverte des instruments traditionnels et de la musique japonaise.",
    level: "débutant",
    category: "Culture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 92,
    title: "Cinéma et animation japonais",
    description: "Introduction au monde des films et des animes japonais.",
    level: "débutant",
    category: "Culture",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 93,
    title: "Littérature japonaise",
    description: "Aperçu des grands auteurs et œuvres de la littérature japonaise.",
    level: "débutant",
    category: "Culture",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 94,
    title: "Religion et spiritualité au Japon",
    description: "Introduction au shintoïsme, au bouddhisme et aux pratiques spirituelles.",
    level: "débutant",
    category: "Culture",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 95,
    title: "Habitation japonaise",
    description: "Découverte des maisons traditionnelles et de l'architecture japonaise.",
    level: "débutant",
    category: "Culture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 96,
    title: "Vêtements traditionnels japonais",
    description: "Le kimono et autres tenues traditionnelles japonaises.",
    level: "débutant",
    category: "Culture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 97,
    title: "Sports et arts martiaux japonais",
    description: "Découverte du sumo, judo, karaté et autres disciplines japonaises.",
    level: "débutant",
    category: "Culture",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 98,
    title: "Jardins japonais",
    description: "L'art des jardins japonais et leur symbolisme.",
    level: "débutant",
    category: "Culture",
    duration: "30 min",
    progress: 0,
  },
  {
    id: 99,
    title: "Cérémonie du thé",
    description: "Histoire et pratique de la cérémonie du thé japonaise.",
    level: "débutant",
    category: "Culture",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 100,
    title: "Le Japon moderne",
    description: "La société japonaise contemporaine et ses contrastes.",
    level: "débutant",
    category: "Culture",
    duration: "35 min",
    progress: 0,
  },

  // ===== NIVEAU INTERMÉDIAIRE (100 leçons) =====
  // Grammaire intermédiaire (101-130)
  {
    id: 101,
    title: "Forme en て des verbes",
    description: "Utilisation et conjugaison de la forme en て des verbes.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 102,
    title: "Forme en ない des verbes",
    description: "Utilisation et conjugaison de la forme en ない des verbes.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 103,
    title: "Forme en た des verbes",
    description: "Utilisation et conjugaison de la forme en た des verbes.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 104,
    title: "Forme potentielle des verbes",
    description: "Comment exprimer la capacité et la possibilité en japonais.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 105,
    title: "Forme passive des verbes",
    description: "Construction et utilisation de la voix passive en japonais.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 106,
    title: "Forme causative des verbes",
    description: "Comment exprimer l'idée de faire faire quelque chose à quelqu'un.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 107,
    title: "Forme causative-passive des verbes",
    description: "Combinaison des formes causative et passive.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 108,
    title: "Forme impérative des verbes",
    description: "Comment donner des ordres et des instructions en japonais.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 109,
    title: "Forme conditionnelle と",
    description: "Utilisation de la particule と pour exprimer des conditions naturelles.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 110,
    title: "Forme conditionnelle ば",
    description: "Utilisation de la forme en ば pour exprimer des conditions hypothétiques.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 111,
    title: "Forme conditionnelle たら",
    description: "Utilisation de la forme en たら pour exprimer des conditions temporelles.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 112,
    title: "Forme conditionnelle なら",
    description: "Utilisation de なら pour introduire des suppositions.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 113,
    title: "Expressions de temps avec 時, 前に et 後で",
    description: "Comment exprimer les relations temporelles en japonais.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 114,
    title: "Expressions de but avec ために et に",
    description: "Comment exprimer le but ou l'objectif d'une action.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 115,
    title: "Expressions de raison avec から et ので",
    description: "Différentes façons d'exprimer la cause ou la raison.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 116,
    title: "Expressions de contraste avec が et けど",
    description: "Comment exprimer le contraste ou la concession.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 117,
    title: "Expressions de choix avec か et など",
    description: "Comment exprimer des alternatives et des exemples.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 118,
    title: "Nominalisation avec の et こと",
    description: "Comment transformer des phrases en noms.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 119,
    title: "Expressions de comparaison",
    description: "Comment comparer des objets ou des personnes en japonais.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 120,
    title: "Expressions de superlatif",
    description: "Comment exprimer le degré le plus élevé d'une qualité.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 121,
    title: "Expressions d'approximation",
    description: "Comment exprimer des quantités ou qualités approximatives.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 122,
    title: "Expressions de changement d'état",
    description: "Comment décrire les changements d'état ou de condition.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 123,
    title: "Expressions de suggestion avec ほうがいい",
    description: "Comment donner des conseils ou faire des suggestions.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 124,
    title: "Expressions de nécessité avec 必要がある et なければならない",
    description: "Comment exprimer l'obligation et la nécessité.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 125,
    title: "Expressions de permission avec てもいい",
    description: "Comment demander et donner la permission.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 126,
    title: "Expressions d'interdiction avec てはいけない",
    description: "Comment exprimer l'interdiction et la prohibition.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 127,
    title: "Expressions de capacité avec ことができる",
    description: "Différentes façons d'exprimer la capacité et la possibilité.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 128,
    title: "Expressions d'effort avec ようにする et ようになる",
    description: "Comment exprimer l'effort et le changement progressif.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 129,
    title: "Expressions d'opinion avec と思う et と考える",
    description: "Comment exprimer ses opinions et ses pensées.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 130,
    title: "Expressions de citation avec と言う et と聞く",
    description: "Comment rapporter les paroles et les informations.",
    level: "intermédiaire",
    category: "Grammaire",
    duration: "45 min",
    progress: 0,
  },

  // Vocabulaire intermédiaire (131-150)
  {
    id: 131,
    title: "Vocabulaire des émotions",
    description: "Termes plus nuancés pour exprimer les sentiments et les émotions.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 132,
    title: "Vocabulaire des relations humaines",
    description: "Termes pour décrire les relations sociales et interpersonnelles.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 133,
    title: "Vocabulaire de l'éducation",
    description: "Termes liés à l'école, l'université et l'apprentissage.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 134,
    title: "Vocabulaire du travail",
    description: "Termes liés à l'emploi, au bureau et à la vie professionnelle.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 135,
    title: "Vocabulaire de la santé",
    description: "Termes médicaux et expressions liées à la santé et au bien-être.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 136,
    title: "Vocabulaire de l'environnement",
    description: "Termes liés à la nature, l'écologie et les problèmes environnementaux.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 137,
    title: "Vocabulaire de la technologie",
    description: "Termes liés aux ordinateurs, à Internet et aux nouvelles technologies.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 138,
    title: "Vocabulaire des médias",
    description: "Termes liés aux journaux, à la télévision et aux médias sociaux.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 139,
    title: "Vocabulaire du sport",
    description: "Termes liés aux sports et aux activités physiques.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 140,
    title: "Vocabulaire des arts",
    description: "Termes liés à la musique, la peinture, le théâtre et autres formes d'art.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 141,
    title: "Vocabulaire de la politique",
    description: "Termes liés au gouvernement, aux élections et aux affaires politiques.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 142,
    title: "Vocabulaire de l'économie",
    description: "Termes liés aux finances, au commerce et à l'économie.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 143,
    title: "Vocabulaire du voyage",
    description: "Termes avancés pour voyager et explorer le Japon.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 144,
    title: "Vocabulaire de la cuisine",
    description: "Termes culinaires et expressions liées à la préparation des aliments.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 145,
    title: "Vocabulaire de la mode",
    description: "Termes liés aux vêtements, aux accessoires et aux tendances.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 146,
    title: "Vocabulaire de l'immobilier",
    description: "Termes liés au logement, à la location et à l'achat de propriétés.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 147,
    title: "Vocabulaire juridique de base",
    description: "Termes juridiques fondamentaux et expressions légales.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 148,
    title: "Vocabulaire des sciences",
    description: "Termes scientifiques de base en japonais.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 149,
    title: "Vocabulaire des loisirs",
    description: "Termes liés aux passe-temps et aux activités récréatives.",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "35 min",
    progress: 0,
  },
  {
    id: 150,
    title: "Vocabulaire des événements de la vie",
    description: "Termes liés aux étapes importantes de la vie (naissance, mariage, etc.).",
    level: "intermédiaire",
    category: "Vocabulaire",
    duration: "40 min",
    progress: 0,
  },

  // Kanji intermédiaires (151-170)
  {
    id: 151,
    title: "Kanji intermédiaires - Partie 1",
    description: "Étude de nouveaux kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 152,
    title: "Kanji intermédiaires - Partie 2",
    description: "Suite de l'étude des kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 153,
    title: "Kanji intermédiaires - Partie 3",
    description: "Poursuite de l'apprentissage des kanji intermédiaires.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 154,
    title: "Kanji intermédiaires - Partie 4",
    description: "Nouveaux kanji de niveau intermédiaire et leurs composés.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 155,
    title: "Kanji intermédiaires - Partie 5",
    description: "Étude approfondie de kanji intermédiaires supplémentaires.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 156,
    title: "Kanji intermédiaires - Partie 6",
    description: "Suite de l'étude des kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 157,
    title: "Kanji intermédiaires - Partie 7",
    description: "Nouveaux kanji intermédiaires et leurs applications.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 158,
    title: "Kanji intermédiaires - Partie 8",
    description: "Poursuite de l'étude des kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 159,
    title: "Kanji intermédiaires - Partie 9",
    description: "Étude de kanji intermédiaires supplémentaires.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 160,
    title: "Kanji intermédiaires - Partie 10",
    description: "Suite de l'apprentissage des kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 161,
    title: "Kanji intermédiaires - Partie 11",
    description: "Nouveaux kanji intermédiaires et leurs utilisations.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 162,
    title: "Kanji intermédiaires - Partie 12",
    description: "Poursuite de l'étude des kanji intermédiaires.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 163,
    title: "Kanji intermédiaires - Partie 13",
    description: "Étude de kanji intermédiaires supplémentaires.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 164,
    title: "Kanji intermédiaires - Partie 14",
    description: "Suite de l'apprentissage des kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 165,
    title: "Kanji intermédiaires - Partie 15",
    description: "Nouveaux kanji intermédiaires et leurs composés.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 166,
    title: "Kanji intermédiaires - Partie 16",
    description: "Poursuite de l'étude des kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 167,
    title: "Kanji intermédiaires - Partie 17",
    description: "Étude de kanji intermédiaires supplémentaires.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 168,
    title: "Kanji intermédiaires - Partie 18",
    description: "Suite de l'apprentissage des kanji de niveau intermédiaire.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 169,
    title: "Kanji intermédiaires - Partie 19",
    description: "Nouveaux kanji intermédiaires et leurs applications.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 170,
    title: "Kanji intermédiaires - Partie 20",
    description: "Révision et pratique des kanji intermédiaires appris.",
    level: "intermédiaire",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },

  // Conversation intermédiaire (171-190)
  {
    id: 171,
    title: "Conversations formelles",
    description: "Comment mener des conversations dans un contexte formel.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 172,
    title: "Conversations informelles",
    description: "Expressions et vocabulaire pour les conversations entre amis.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 173,
    title: "Débats et discussions",
    description: "Comment exprimer et défendre ses opinions en japonais.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 174,
    title: "Narration d'histoires",
    description: "Comment raconter des histoires et des anecdotes en japonais.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 175,
    title: "Descriptions détaillées",
    description: "Comment décrire des personnes, des lieux et des situations en détail.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 176,
    title: "Explications et instructions",
    description: "Comment expliquer des concepts et donner des instructions claires.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 177,
    title: "Conversations téléphoniques avancées",
    description: "Expressions et stratégies pour des conversations téléphoniques plus complexes.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 178,
    title: "Entretiens et interviews",
    description: "Comment répondre à des questions dans un contexte d'entretien.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 179,
    title: "Présentations orales",
    description: "Comment préparer et donner une présentation en japonais.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 180,
    title: "Négociations de base",
    description: "Expressions et stratégies pour négocier en japonais.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 181,
    title: "Résolution de problèmes",
    description: "Comment discuter et résoudre des problèmes en japonais.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 182,
    title: "Conversations sur l'actualité",
    description: "Comment discuter des nouvelles et des événements actuels.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 183,
    title: "Discussions culturelles",
    description: "Comment parler de différences et de similitudes culturelles.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 184,
    title: "Conversations sur les voyages",
    description: "Comment parler de vos expériences de voyage et de vos projets.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 185,
    title: "Discussions sur les films et la littérature",
    description: "Comment parler de films, de livres et d'autres œuvres culturelles.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 186,
    title: "Conversations sur la technologie",
    description: "Comment discuter des nouvelles technologies et de leur impact.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 187,
    title: "Discussions sur l'environnement",
    description: "Comment parler des problèmes environnementaux et des solutions.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 188,
    title: "Discussions sur la santé",
    description: "Comment parler de la santé, du bien-être et des soins médicaux.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 189,
    title: "Conversations professionnelles",
    description: "Comment communiquer efficacement dans un environnement de travail.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 190,
    title: "Expressions idiomatiques courantes",
    description: "Comprendre et utiliser des expressions idiomatiques japonaises.",
    level: "intermédiaire",
    category: "Conversation",
    duration: "45 min",
    progress: 0,
  },

  // Compréhension et expression écrite (191-200)
  {
    id: 191,
    title: "Lecture de textes informatifs",
    description: "Stratégies pour comprendre des articles et des textes informatifs.",
    level: "intermédiaire",
    category: "Lecture",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 192,
    title: "Lecture de textes narratifs",
    description: "Comment lire et comprendre des histoires et des récits.",
    level: "intermédiaire",
    category: "Lecture",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 193,
    title: "Rédaction d'emails et de messages",
    description: "Comment écrire des emails formels et informels en japonais.",
    level: "intermédiaire",
    category: "Écriture",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 194,
    title: "Rédaction de textes descriptifs",
    description: "Comment écrire des descriptions détaillées en japonais.",
    level: "intermédiaire",
    category: "Écriture",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 195,
    title: "Rédaction de textes narratifs",
    description: "Comment écrire des histoires et des anecdotes en japonais.",
    level: "intermédiaire",
    category: "Écriture",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 196,
    title: "Rédaction d'opinions et d'arguments",
    description: "Comment exprimer et défendre ses opinions par écrit.",
    level: "intermédiaire",
    category: "Écriture",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 197,
    title: "Compréhension de documents authentiques",
    description: "Comment comprendre des documents réels comme des brochures et des menus.",
    level: "intermédiaire",
    category: "Lecture",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 198,
    title: "Lecture de manga et de bandes dessinées",
    description: "Stratégies pour comprendre le japonais dans les mangas.",
    level: "intermédiaire",
    category: "Lecture",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 199,
    title: "Prise de notes en japonais",
    description: "Techniques efficaces pour prendre des notes en japonais.",
    level: "intermédiaire",
    category: "Écriture",
    duration: "40 min",
    progress: 0,
  },
  {
    id: 200,
    title: "Résumés et synthèses",
    description: "Comment résumer des textes et des informations en japonais.",
    level: "intermédiaire",
    category: "Écriture",
    duration: "45 min",
    progress: 0,
  },

  // ===== NIVEAU AVANCÉ (100 leçons) =====
  // Grammaire avancée (201-220)
  {
    id: 201,
    title: "Structures grammaticales complexes",
    description: "Maîtrise des structures grammaticales avancées en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 202,
    title: "Nuances des particules avancées",
    description: "Utilisation fine et nuancée des particules japonaises.",
    level: "avancé",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 203,
    title: "Expressions de modalité",
    description: "Comment exprimer la probabilité, la certitude et le doute.",
    level: "avancé",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 204,
    title: "Expressions de respect et d'humilité",
    description: "Utilisation appropriée du langage honorifique et humble.",
    level: "avancé",
    category: "Grammaire",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 205,
    title: "Keigo - Langage honorifique",
    description: "Étude approfondie du langage honorifique japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 206,
    title: "Kenjougo - Langage humble",
    description: "Étude approfondie du langage humble japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 207,
    title: "Teineigo - Langage poli",
    description: "Maîtrise des nuances du langage poli japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 208,
    title: "Expressions passives avancées",
    description: "Utilisations complexes de la voix passive en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 209,
    title: "Expressions causatives avancées",
    description: "Utilisations complexes de la forme causative en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 210,
    title: "Expressions conditionnelles avancées",
    description: "Formes conditionnelles complexes et leurs nuances.",
    level: "avancé",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 211,
    title: "Nominalisation avancée",
    description: "Techniques complexes de nominalisation en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 212,
    title: "Expressions de concession",
    description: "Comment exprimer la concession et l'opposition en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 213,
    title: "Expressions de but et de résultat",
    description: "Façons avancées d'exprimer le but et le résultat.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 214,
    title: "Expressions de changement et de transition",
    description: "Comment exprimer les changements d'état de manière nuancée.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 215,
    title: "Expressions d'approximation et d'incertitude",
    description: "Comment exprimer l'approximation et l'incertitude en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 216,
    title: "Expressions de regret et de reproche",
    description: "Comment exprimer le regret, le reproche et la critique.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 217,
    title: "Expressions d'emphase et de mise en relief",
    description: "Comment mettre l'accent sur certains éléments de la phrase.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 218,
    title: "Expressions de restriction et de limitation",
    description: "Comment exprimer des restrictions et des limitations en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 219,
    title: "Expressions de gradation et de degré",
    description: "Comment exprimer différents degrés et niveaux en japonais.",
    level: "avancé",
    category: "Grammaire",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 220,
    title: "Structures de phrases complexes",
    description: "Maîtrise des phrases complexes avec plusieurs propositions.",
    level: "avancé",
    category: "Grammaire",
    duration: "60 min",
    progress: 0,
  },

  // Kanji avancés (221-240)
  {
    id: 221,
    title: "Kanji avancés - Partie 1",
    description: "Étude de kanji complexes de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 222,
    title: "Kanji avancés - Partie 2",
    description: "Suite de l'étude des kanji de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 223,
    title: "Kanji avancés - Partie 3",
    description: "Poursuite de l'apprentissage des kanji avancés.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 224,
    title: "Kanji avancés - Partie 4",
    description: "Nouveaux kanji de niveau avancé et leurs composés.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 225,
    title: "Kanji avancés - Partie 5",
    description: "Étude approfondie de kanji avancés supplémentaires.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 226,
    title: "Kanji avancés - Partie 6",
    description: "Suite de l'étude des kanji de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 227,
    title: "Kanji avancés - Partie 7",
    description: "Nouveaux kanji avancés et leurs applications.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 228,
    title: "Kanji avancés - Partie 8",
    description: "Poursuite de l'étude des kanji de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 229,
    title: "Kanji avancés - Partie 9",
    description: "Étude de kanji avancés supplémentaires.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 230,
    title: "Kanji avancés - Partie 10",
    description: "Suite de l'apprentissage des kanji de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 231,
    title: "Kanji avancés - Partie 11",
    description: "Nouveaux kanji avancés et leurs utilisations.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 232,
    title: "Kanji avancés - Partie 12",
    description: "Poursuite de l'étude des kanji avancés.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 233,
    title: "Kanji avancés - Partie 13",
    description: "Étude de kanji avancés supplémentaires.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 234,
    title: "Kanji avancés - Partie 14",
    description: "Suite de l'apprentissage des kanji de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 235,
    title: "Kanji avancés - Partie 15",
    description: "Nouveaux kanji avancés et leurs composés.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 236,
    title: "Kanji avancés - Partie 16",
    description: "Poursuite de l'étude des kanji de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 237,
    title: "Kanji avancés - Partie 17",
    description: "Étude de kanji avancés supplémentaires.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 238,
    title: "Kanji avancés - Partie 18",
    description: "Suite de l'apprentissage des kanji de niveau avancé.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 239,
    title: "Kanji avancés - Partie 19",
    description: "Nouveaux kanji avancés et leurs applications.",
    level: "avancé",
    category: "Kanji",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 240,
    title: "Kanji avancés - Partie 20",
    description: "Révision et pratique des kanji avancés appris.",
    level: "avancé",
    category: "Kanji",
    duration: "70 min",
    progress: 0,
  },

  // Compréhension et expression écrite avancées (241-260)
  {
    id: 241,
    title: "Lecture de textes littéraires",
    description: "Stratégies pour comprendre la littérature japonaise.",
    level: "avancé",
    category: "Lecture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 242,
    title: "Lecture de textes académiques",
    description: "Comment lire et comprendre des textes académiques en japonais.",
    level: "avancé",
    category: "Lecture",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 243,
    title: "Lecture de textes journalistiques",
    description: "Stratégies pour comprendre les articles de presse japonais.",
    level: "avancé",
    category: "Lecture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 244,
    title: "Lecture de textes techniques",
    description: "Comment comprendre des documents techniques en japonais.",
    level: "avancé",
    category: "Lecture",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 245,
    title: "Rédaction d'essais",
    description: "Comment structurer et rédiger des essais en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 246,
    title: "Rédaction de rapports",
    description: "Comment rédiger des rapports formels en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 247,
    title: "Rédaction de textes argumentatifs",
    description: "Comment construire et présenter des arguments en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 248,
    title: "Rédaction de textes créatifs",
    description: "Comment écrire des histoires et des poèmes en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 249,
    title: "Analyse de textes",
    description: "Comment analyser et interpréter des textes japonais.",
    level: "avancé",
    category: "Lecture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 250,
    title: "Résumés et synthèses avancés",
    description: "Techniques avancées pour résumer des textes complexes.",
    level: "avancé",
    category: "Écriture",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 251,
    title: "Traduction japonais-français",
    description: "Principes et techniques de traduction du japonais vers le français.",
    level: "avancé",
    category: "Traduction",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 252,
    title: "Traduction français-japonais",
    description: "Principes et techniques de traduction du français vers le japonais.",
    level: "avancé",
    category: "Traduction",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 253,
    title: "Interprétation de textes littéraires",
    description: "Comment interpréter et analyser la littérature japonaise.",
    level: "avancé",
    category: "Lecture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 254,
    title: "Lecture critique",
    description: "Développer une approche critique des textes japonais.",
    level: "avancé",
    category: "Lecture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 255,
    title: "Rédaction professionnelle",
    description: "Comment rédiger des documents professionnels en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 256,
    title: "Rédaction académique",
    description: "Comment rédiger des textes académiques en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 257,
    title: "Styles d'écriture japonais",
    description: "Étude des différents styles d'écriture en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 258,
    title: "Lecture de documents historiques",
    description: "Comment lire et comprendre des textes historiques japonais.",
    level: "avancé",
    category: "Lecture",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 259,
    title: "Analyse du discours",
    description: "Comment analyser la structure et le contenu du discours japonais.",
    level: "avancé",
    category: "Lecture",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 260,
    title: "Rédaction de discours",
    description: "Comment préparer et rédiger des discours en japonais.",
    level: "avancé",
    category: "Écriture",
    duration: "60 min",
    progress: 0,
  },

  // Japonais des affaires (261-280)
  {
    id: 261,
    title: "Introduction au japonais des affaires",
    description: "Bases du langage et de l'étiquette des affaires au Japon.",
    level: "avancé",
    category: "Affaires",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 262,
    title: "Vocabulaire des affaires - Partie 1",
    description: "Termes essentiels pour le monde des affaires japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 263,
    title: "Vocabulaire des affaires - Partie 2",
    description: "Termes avancés pour le monde des affaires japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 264,
    title: "Emails professionnels en japonais",
    description: "Comment rédiger des emails professionnels efficaces.",
    level: "avancé",
    category: "Affaires",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 265,
    title: "Réunions d'affaires en japonais",
    description: "Comment participer et diriger des réunions en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 266,
    title: "Présentations professionnelles",
    description: "Comment préparer et donner des présentations d'affaires.",
    level: "avancé",
    category: "Affaires",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 267,
    title: "Négociations commerciales",
    description: "Stratégies et expressions pour les négociations en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 268,
    title: "Rapports d'entreprise",
    description: "Comment rédiger et présenter des rapports d'entreprise.",
    level: "avancé",
    category: "Affaires",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 269,
    title: "Entretiens d'embauche",
    description: "Comment se préparer et réussir un entretien d'embauche en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 270,
    title: "CV et lettres de motivation",
    description: "Comment rédiger un CV et une lettre de motivation en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 271,
    title: "Téléphone d'affaires",
    description: "Expressions et protocoles pour les appels téléphoniques professionnels.",
    level: "avancé",
    category: "Affaires",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 272,
    title: "Accueil des clients",
    description: "Comment accueillir et servir des clients en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "50 min",
    progress: 0,
  },
  {
    id: 273,
    title: "Gestion de projet en japonais",
    description: "Vocabulaire et expressions pour la gestion de projet.",
    level: "avancé",
    category: "Affaires",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 274,
    title: "Marketing en japonais",
    description: "Termes et concepts du marketing en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 275,
    title: "Finance et comptabilité",
    description: "Vocabulaire japonais de la finance et de la comptabilité.",
    level: "avancé",
    category: "Affaires",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 276,
    title: "Ressources humaines",
    description: "Termes et concepts des ressources humaines en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 277,
    title: "Droit des affaires",
    description: "Introduction au vocabulaire juridique des affaires en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 278,
    title: "Relations clients",
    description: "Comment gérer les relations clients en japonais.",
    level: "avancé",
    category: "Affaires",
    duration: "55 min",
    progress: 0,
  },
  {
    id: 279,
    title: "Résolution de problèmes professionnels",
    description: "Comment aborder et résoudre des problèmes en milieu professionnel.",
    level: "avancé",
    category: "Affaires",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 280,
    title: "Étiquette d'entreprise japonaise",
    description: "Règles et normes de comportement dans les entreprises japonaises.",
    level: "avancé",
    category: "Affaires",
    duration: "55 min",
    progress: 0,
  },

  // Préparation JLPT (281-300)
  {
    id: 281,
    title: "Introduction au JLPT",
    description: "Présentation du test et stratégies générales de préparation.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "45 min",
    progress: 0,
  },
  {
    id: 282,
    title: "Vocabulaire JLPT N3",
    description: "Révision et pratique du vocabulaire pour le niveau N3.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 283,
    title: "Grammaire JLPT N3",
    description: "Révision et pratique des points de grammaire pour le niveau N3.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 284,
    title: "Kanji JLPT N3",
    description: "Révision et pratique des kanji pour le niveau N3.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 285,
    title: "Compréhension écrite JLPT N3",
    description: "Stratégies et exercices pour la section de lecture du N3.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 286,
    title: "Compréhension orale JLPT N3",
    description: "Stratégies et exercices pour la section d'écoute du N3.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "60 min",
    progress: 0,
  },
  {
    id: 287,
    title: "Vocabulaire JLPT N2",
    description: "Révision et pratique du vocabulaire pour le niveau N2.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 288,
    title: "Grammaire JLPT N2",
    description: "Révision et pratique des points de grammaire pour le niveau N2.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "70 min",
    progress: 0,
  },
  {
    id: 289,
    title: "Kanji JLPT N2",
    description: "Révision et pratique des kanji pour le niveau N2.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 290,
    title: "Compréhension écrite JLPT N2",
    description: "Stratégies et exercices pour la section de lecture du N2.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 291,
    title: "Compréhension orale JLPT N2",
    description: "Stratégies et exercices pour la section d'écoute du N2.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "65 min",
    progress: 0,
  },
  {
    id: 292,
    title: "Vocabulaire JLPT N1",
    description: "Révision et pratique du vocabulaire pour le niveau N1.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "70 min",
    progress: 0,
  },
  {
    id: 293,
    title: "Grammaire JLPT N1",
    description: "Révision et pratique des points de grammaire pour le niveau N1.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "75 min",
    progress: 0,
  },
  {
    id: 294,
    title: "Kanji JLPT N1",
    description: "Révision et pratique des kanji pour le niveau N1.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "70 min",
    progress: 0,
  },
  {
    id: 295,
    title: "Compréhension écrite JLPT N1",
    description: "Stratégies et exercices pour la section de lecture du N1.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "70 min",
    progress: 0,
  },
  {
    id: 296,
    title: "Compréhension orale JLPT N1",
    description: "Stratégies et exercices pour la section d'écoute du N1.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "70 min",
    progress: 0,
  },
  {
    id: 297,
    title: "Tests blancs JLPT N3",
    description: "Entraînement avec des examens complets de niveau N3.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "120 min",
    progress: 0,
  },
  {
    id: 298,
    title: "Tests blancs JLPT N2",
    description: "Entraînement avec des examens complets de niveau N2.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "140 min",
    progress: 0,
  },
  {
    id: 299,
    title: "Tests blancs JLPT N1",
    description: "Entraînement avec des examens complets de niveau N1.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "170 min",
    progress: 0,
  },
  {
    id: 300,
    title: "Stratégies finales pour le JLPT",
    description: "Conseils de dernière minute et stratégies pour réussir l'examen.",
    level: "avancé",
    category: "Préparation JLPT",
    duration: "60 min",
    progress: 0,
  },
]

